image: cstheriot/aurelia-cli:latest
options:
  docker: true
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
      - au test
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
      - au test
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
- echo -e "Host steembottracker.net\n\StrictHostKeyChecking no\n" >> ~./ssh/config
***REMOVED***
- ssh -i ./deploy-key ubuntu@steembotracker.net pwd
