***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
  - steembottracker.net
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
- ssh -i ./deploy-key ubuntu@steembottracker.net pwd
