image: cstheriot/aurelia-cli:latest

options:
  docker: true

***REMOVED***
***REMOVED***
***REMOVED***
      - step:
  ***REMOVED***
    ***REMOVED***
    ***REMOVED***
          - au test
***REMOVED***
      - step:
  ***REMOVED***
    ***REMOVED***
    ***REMOVED***
          - au test
