image: cstheriot/aurelia-cli:latest
options:
  docker: true
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
      - au test
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
      - au test
***REMOVED***
***REMOVED***
  -in steem-engine-deploy-key.enc -out ~\/steem-engine-deploy-key -d
***REMOVED***
- chmod 400 ./steem-engine-deploy-key
- echo -e "Host steembottracker.net\n\StrictHostKeyChecking no\n" >> ~./ssh/config
- ssh-add ./steem-engine-deploy-key
- ssh -i ./steem-engine-deploy-key ubuntu@steembotracker.net pwd
