image: cstheriot/aurelia-cli:latest
options:
  docker: true
***REMOVED***
***REMOVED***
  - steembottracker.net
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
      - au test
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
      - au test
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
- ssh -i ./deploy-key ubuntu@steembottracker.net pwd
