image: cstheriot/aurelia-cli:latest

options:
  docker: true

pipelines:
  branches:
    master:
      - step:
        script:
          - yarn
          - au build --env prod
          - au test
    develop:
      - step:
        script:
          - yarn
          - au build --env dev
          - au test
