language: node_js
node_js:
  - "10"
pipelines:
  branches:
    master:
    - step: 
      script:
      - yarn
      - au build --env prod
      - au test --passWithNoTests
    develop:
    - step: 
      script:
      - yarn
      - au build --env dev
      - au test --passWithNoTests
before_install:
- openssl aes-256-cbc -K $encrypted_134e9820d8ee_key -iv $encrypted_134e9820d8ee_iv
  -in deploy-key.enc -out ./deploy-key -d
- npm install aurelia-cli -g
- eval "$(ssh-agent -s)"
- chmod 400 ./deploy-key
- ssh-add ./deploy-key
- ssh-keyscan -t $TRAVIS_SSH_KEY_TYPES -H $HOST 2>&1 | tee -a $HOME/.ssh/known_hosts
- ssh -i ./deploy-key ubuntu@$HOST pwd
