image: cstheriot/aurelia-cli:latest
options:
  docker: true
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
      - au test
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
      - au test
***REMOVED***
***REMOVED***
  -in steem-engine-deploy-key.enc -out ~\/steem-engine-deploy-key -d
